= Code download
Andreas Deininger andreas@deininger.net

== Embedded Wizard project source code

In the course of this tutorial, we gradually authored and extended a sample application. You may download the whole project including all source files, packed inside a .zip archive by using the links given in <<tab:DownloadCode>> below:

.Embedded Wizard project source code packages 
[[tab:DownloadCode]]
[width=75%, cols="<40,^35", options="header", grid=rows, frame=topbot]
|===
| Lesson / chapter                                                           | Project zip archive 
| xref::HelloWorld.adoc[Getting started with 'Hello world']                  | link:{attachmentsdir}/HelloWorldTutorial.zip[HelloWorldTutorial.zip]
| xref::FirstComponent.adoc[Adding your first GUI component]                 | link:{attachmentsdir}/FirstComponentTutorial.zip[FirstComponentTutorial.zip]
| xref::ComponentReusability.adoc[Making your GUI component truly reusable]  | link:{attachmentsdir}/ReusableComponentTutorial.zip[ReusableComponentTutorial.zip]
| xref::DeviceIntegrationBrowser.adoc[Integrating with your browser device] | link:{attachmentsdir}/DeviceIntegrationTutorial.zip[DeviceIntegrationTutorial.zip]
| xref::LocalizingYourApplication.adoc[Localizing your application]          | link:{attachmentsdir}/LocalizationTutorial.zip[LocalizationTutorial.zip]
|===

NOTE: The zip-archive represents the project once the lesson was *finalized*. If you want to work through a lesson, and need the project code as starting point, simply take the zip archive from the lesson before.

== Source code of the tutorial website

This tutorial project in its entirety (Embedded Wizard code + code tutorial site) is hosted on https://github.com/deining/EmWiTutorial[GitHub^]. For further information refer to the https://github.com/deining/EmWiTutorial/blob/master/README.md[README^] file of this repository.
